<a href="https://colab.research.google.com/github/musabegumm/DSC110/blob/main/ML_Data_Prep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Import libraries. Note the new library SciKit Learn
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

Above, coding pandas as pd in short for the imported library
And then import it from sklearn.preprocessing to import StandardScaler

In [3]:
#Read the CSV file
df = pd.read_csv('https://raw.githubusercontent.com/osoliman/DSC110/refs/heads/main/Datasets/nhanes_final.csv')

Below, vefifying to see if the dataframe is runing as as pd (pandas)

In [4]:
df.head()

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0
1,130379.0,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0,5.6,99.0
2,130380.0,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0,6.2,156.0
3,130381.0,2.0,5.0,7.0,NaN,23.8,120.1,NaN,2.0,NaN,NaN
4,130382.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN

The line below, filters the df to keep the rows only where the patients are over 18 years

In [7]:
#Filtering
df = df[df['age'] >= 18].copy()

Code below, deletes the columns that are specifically mentioned inside the brecket.

In [16]:
df = df.drop(columns=['id', 'hba1c', 'fasting_glucose'])

KeyError: "['id', 'hba1c', 'fasting_glucose'] not found in axis"

In [13]:
#Mapping labels, here we're translating the numbers into words
gender_map     = {1.0: 'Male', 2.0: 'Female'}
race_map       = {1.0: 'Mexican American', 2.0: 'Other Hispanic',
                  3.0: 'White', 4.0: 'Black',
                  6.0: 'Asian', 7.0: 'Other'}
education_map  = {1.0: 'Less than 9th', 2.0: '9-11th grade',
                  3.0: 'High school',   4.0: 'Some college',
                  5.0: 'College grad',  9.0: 'Do not know'}

df['gender']         = df['gender'].map(gender_map)
df['race_ethnicity'] = df['race_ethnicity'].map(race_map)
df['education']      = df['education'].map(education_map)

In [15]:
#This code is counting the how many missing values are in each columns of the df and putting the total
df.isna().sum()

gender            8153
age                  0
race_ethnicity    8153
education         8153
bmi               1918
height_cm         1891
systolic_bp       2030
has_diabetes         3
dtype: int64

# Filtering

In [17]:
df = df[df['age'] >= 18].copy()

In [19]:
#This shows the size of the df, so there are total of 8153 rows and 8 columns
df.shape

(8153, 8)

# Dropping Columns

In [21]:
#This code will give only the first 5 columns of the dataframe where the counting starts from 0.
df.head()

,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes
0,NaN,43.0,NaN,NaN,27.0,179.5,135.0,2.0
1,NaN,66.0,NaN,NaN,33.5,174.2,121.0,2.0
2,NaN,44.0,NaN,NaN,29.7,152.9,111.0,1.0
6,NaN,43.0,NaN,NaN,NaN,NaN,NaN,2.0
7,NaN,65.0,NaN,NaN,NaN,NaN,NaN,2.0

In [25]:
#This code will get rid off the rows inside the brecket.
df=df.drop(columns=['id' , 'hba1c' , 'fasting_glucose'])

KeyError: "['id', 'hba1c', 'fasting_glucose'] not found in axis"

In [32]:
#Dictionaries, the code here converts the numerical into readable texts
gender_map     = {1.0: 'Male', 2.0: 'Female'}
race_map       = {1.0: 'Mexican American', 2.0: 'Other Hispanic',
                  3.0: 'White', 4.0: 'Black',
                  6.0: 'Asian', 7.0: 'Other'}
education_map  = {1.0: 'Less than 9th', 2.0: '9-11th grade',
                  3.0: 'High school',   4.0: 'Some college',
                  5.0: 'College grad',  9.0: 'Do not know'}

df['gender']         = df['gender'].map(gender_map)
df['race_ethnicity'] = df['race_ethnicity'].map(race_map)
df['education']      = df['education'].map(education_map)

In [36]:
#This code is replacing the numbers with texts. 1 --> male and 2 --> female
df['gender'] = df['gender'].map(gender_map)

In [35]:
df['gender'].head()

0    NaN
1    NaN
2    NaN
6    NaN
7    NaN
Name: gender, dtype: object

In [37]:
df['race_ethnicity']

0        NaN
1        NaN
2        NaN
6        NaN
7        NaN
        ...
11927    NaN
11929    NaN
11930    NaN
11931    NaN
11932    NaN
Name: race_ethnicity, Length: 8153, dtype: object

In [40]:
df['education']=df['education'].map(education_map)

In [41]:
df['education'].head()

0    NaN
1    NaN
2    NaN
6    NaN
7    NaN
Name: education, dtype: object

In [42]:
df.isna().sum()

gender            8153
age                  0
race_ethnicity    8153
education         8153
bmi               1918
height_cm         1891
systolic_bp       2030
has_diabetes         3
dtype: int64

In [43]:
#Checking for missing values
df.isna().sum()

gender            8153
age                  0
race_ethnicity    8153
education         8153
bmi               1918
height_cm         1891
systolic_bp       2030
has_diabetes         3
dtype: int64

In [44]:
#This code here fills in missing BMI with average BMI
df['bmi'] = df['bmi'].fillna(df['bmi'].mean())

In [45]:
df.isna().sum()

gender            8153
age                  0
race_ethnicity    8153
education         8153
bmi                  0
height_cm         1891
systolic_bp       2030
has_diabetes         3
dtype: int64

In [47]:
#This also fills the missing values of height_cm and systolic_bp with their average numbers
df['height_cm'] = df['height_cm'].fillna(df['height_cm'].mean())
df['systolic_bp'] = df['systolic_bp'].fillna(df['systolic_bp'].mean())

In [48]:
df.isna().sum()

gender            8153
age                  0
race_ethnicity    8153
education         8153
bmi                  0
height_cm            0
systolic_bp          0
has_diabetes         3
dtype: int64

In [49]:
#It removes all rows where the education is missing
df = df.dropna(subset=['education']).copy()

# One Hot Encodoing

In [54]:
#This code convers the categorical columns into numerical columns
df = pd.get_dummies(df, columns=['gender', 'race_ethnicity', 'education'],
                    drop_first=True)

KeyError: "None of [Index(['gender', 'race_ethnicity', 'education'], dtype='object')] are in the [columns]"

In [53]:
df.head()

Empty DataFrame
Columns: [age, bmi, height_cm, systolic_bp, has_diabetes]
Index: []

## Scaling Numerical Numbers

In [56]:
#Scaling the numerical columns
numeric_cols = ['age', 'bmi', 'height_cm', 'systolic_bp']
scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

ValueError: Found array with 0 sample(s) (shape=(0, 4)) while a minimum of 1 is required by StandardScaler.

In [57]:
print(round(df['age'].mean(),2))

nan

# Train/Test Split

In [58]:
#This seperate the dataset for features and target
X = df.drop(columns=['has_diabetes'])
#Splits the data for training testing the sets
y = df['has_diabetes']